"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var floyd_steinberg_1 = require("./floyd-steinberg");
exports.FloydSteinberg = floyd_steinberg_1.dither;
var jarvis_judice_ninke_1 = require("./jarvis-judice-ninke");
exports.JarvisJudiceNinke = jarvis_judice_ninke_1.dither;
var sierra_1 = require("./sierra");
exports.Sierra = sierra_1.dither;
var sierra_lite_1 = require("./sierra-lite");
exports.SierraLite = sierra_lite_1.dither;
var sierra_two_row_1 = require("./sierra-two-row");
exports.SierraTwoRow = sierra_two_row_1.dither;
