"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const i_1 = require("../rgb/i");
const util_1 = require("./util");
const bgʹ = 40;
const bgʺ = 60 + bgʹ;
const bg = util_1.wrap(util_1.esc(9 + bgʹ));
exports.rgb = (rgb) => bg(util_1.esc(bgʹ + 8, 2, i_1.r(rgb), i_1.g(rgb), i_1.b(rgb)));
exports.black = bg(util_1.esc(bgʹ + 0)), exports.red = bg(util_1.esc(bgʹ + 1)), exports.green = bg(util_1.esc(bgʹ + 2)), exports.yellow = bg(util_1.esc(bgʹ + 3)), exports.blue = bg(util_1.esc(bgʹ + 4)), exports.magenta = bg(util_1.esc(bgʹ + 5)), exports.cyan = bg(util_1.esc(bgʹ + 6)), exports.lightGray = bg(util_1.esc(bgʹ + 7));
exports.darkGray = bg(util_1.esc(bgʺ + 0)), exports.lightRed = bg(util_1.esc(bgʺ + 1)), exports.lightGreen = bg(util_1.esc(bgʺ + 2)), exports.lightYellow = bg(util_1.esc(bgʺ + 3)), exports.lightBlue = bg(util_1.esc(bgʺ + 4)), exports.lightMagenta = bg(util_1.esc(bgʺ + 5)), exports.lightCyan = bg(util_1.esc(bgʺ + 6)), exports.white = bg(util_1.esc(bgʺ + 7));
