"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const i_1 = require("../rgb/i");
const util_1 = require("./util");
const fgʹ = 30;
const fgʺ = 60 + fgʹ;
const fg = util_1.wrap(util_1.esc(9 + fgʹ));
exports.rgb = (rgb) => fg(util_1.esc(fgʹ + 8, 2, i_1.r(rgb), i_1.g(rgb), i_1.b(rgb)));
exports.black = fg(util_1.esc(fgʹ + 0)), exports.red = fg(util_1.esc(fgʹ + 1)), exports.green = fg(util_1.esc(fgʹ + 2)), exports.yellow = fg(util_1.esc(fgʹ + 3)), exports.blue = fg(util_1.esc(fgʹ + 4)), exports.magenta = fg(util_1.esc(fgʹ + 5)), exports.cyan = fg(util_1.esc(fgʹ + 6)), exports.lightGray = fg(util_1.esc(fgʹ + 7));
exports.darkGray = fg(util_1.esc(fgʺ + 0)), exports.lightRed = fg(util_1.esc(fgʺ + 1)), exports.lightGreen = fg(util_1.esc(fgʺ + 2)), exports.lightYellow = fg(util_1.esc(fgʺ + 3)), exports.lightBlue = fg(util_1.esc(fgʺ + 4)), exports.lightMagenta = fg(util_1.esc(fgʺ + 5)), exports.lightCyan = fg(util_1.esc(fgʺ + 6)), exports.white = fg(util_1.esc(fgʺ + 7));
